import jsPDF from "jspdf";

type Issue = { title: string; explanation: string; fix: string; severity: "error" | "warning" | "pass" };
type AuditCategory = { category: string; issues: Issue[] };

export function exportAuditPdf(audit: {
  domain: string;
  seo_score: number;
  created_at: string;
  issues: AuditCategory[];
}) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  let y = 20;

  const checkPage = (need: number) => {
    if (y + need > 270) {
      doc.addPage();
      y = 20;
    }
  };

  // Title
  doc.setFontSize(20);
  doc.setTextColor(34, 197, 94);
  doc.text("RankSprout SEO Audit", 14, y);
  y += 10;

  doc.setFontSize(11);
  doc.setTextColor(100);
  doc.text(`Domain: ${audit.domain}`, 14, y);
  y += 6;
  doc.text(`Date: ${new Date(audit.created_at).toLocaleDateString()}`, 14, y);
  y += 6;
  doc.text(`Score: ${audit.seo_score} / 100`, 14, y);
  y += 12;

  // Score bar
  doc.setDrawColor(200);
  doc.setFillColor(230, 230, 230);
  doc.roundedRect(14, y, pageWidth - 28, 6, 3, 3, "F");
  const barColor = audit.seo_score >= 70 ? [34, 197, 94] : audit.seo_score >= 40 ? [245, 158, 11] : [239, 68, 68];
  doc.setFillColor(barColor[0], barColor[1], barColor[2]);
  doc.roundedRect(14, y, (pageWidth - 28) * (audit.seo_score / 100), 6, 3, 3, "F");
  y += 16;

  const severityColors: Record<string, [number, number, number]> = {
    error: [239, 68, 68],
    warning: [245, 158, 11],
    pass: [34, 197, 94],
  };

  for (const cat of audit.issues) {
    checkPage(20);
    doc.setFontSize(14);
    doc.setTextColor(30);
    doc.text(cat.category, 14, y);
    y += 8;

    for (const issue of cat.issues || []) {
      checkPage(24);
      const color = severityColors[issue.severity] || severityColors.warning;
      doc.setFillColor(color[0], color[1], color[2]);
      doc.circle(18, y - 1.5, 2, "F");

      doc.setFontSize(10);
      doc.setTextColor(30);
      doc.text(issue.title, 24, y);
      y += 5;

      doc.setFontSize(8);
      doc.setTextColor(100);
      const explanation = doc.splitTextToSize(issue.explanation, pageWidth - 40);
      doc.text(explanation, 24, y);
      y += explanation.length * 3.5 + 2;

      doc.setTextColor(34, 197, 94);
      const fix = doc.splitTextToSize(`Fix: ${issue.fix}`, pageWidth - 40);
      doc.text(fix, 24, y);
      y += fix.length * 3.5 + 6;
    }
    y += 4;
  }

  // Footer
  checkPage(10);
  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text("Generated by RankSprout — ranksprout.app", 14, 285);

  doc.save(`seo-audit-${audit.domain}-${Date.now()}.pdf`);
}
